version: "3"
services:
    nodered: 
        image: nodered/node-red
        ports:
            - 1880:1880
        env_file:
            - nodered.env
        volumes:
            - nodered-data:/data
    influxdb: 
        image: influxdb
        ports:
            - 8086:8086
        volumes:
            - influxdb:/var/lib/influxdb
    mosquitto: 
        image: eclipse-mosquitto
        ports:
            - 1883:1883

volumes:
    nodered-data:
    influxdb:
