version: "3"
services:
    nodered: 
        image: nodered/node-red
        ports:
            - 1880:1880
        environment:
            FLOWS: "flows.json"
        volumes:
            - nodered-data:/data
        networks:
            - backend
    influxdb: 
        image: influxdb
        ports:
            - 8086:8086
        volumes:
            - influxdb:/var/lib/influxdb
        networks:
            - backend
    mosquitto: 
        image: eclipse-mosquitto
        ports:
            - 1883:1883
        networks:
            - backend

networks:
    frontend:
    backend:

volumes:
    nodered-data:
    influxdb:
