version: "3"
services:
    nodered: 
        image: nodered/node-red
        ports:
            - 1880:1880
        volumes:
            - nodered-data:/data
        networks:
            - frontend

networks:
  frontend:

volumes:
  nodered-data:
